baseURL: "https://sophiamo.github.io/portfolio/"
title: Sophia Mo
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 1
        - name: Teaching
          url: courses/
          weight: 2

params:
    description: "I am a PhD candidate in Economics at Harvard University. My research fields are macroeconomics and labor economics."
    author: Sophia Mo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    social: true
    profileMode:
          enabled: true
          title: Sophia Mo
          subtitle:
              I am a PhD candidate in Economics at Harvard University. My research fields are macroeconomics and labor economics. My current work studies the roles of coworkers on labor mobility and reallocation. You can reach me at yiningmo@fas.harvard.edu <br><br>
              **In 2024/2025, I will be on the academic job market.**
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Sophia Mo
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:yiningmo@fas.harvard.edu

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Sophia Mo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
